---
title: "numeric results interval arithmetic"
output: html_document
author: GE Ryan
---



```{r}
numeric_results <- numeric_data %>%
  as_tibble %>% 
  mutate(
    zpw = q1.1.1 - q1.2.2 -              1*(q1.2.2 - q1.2.2),
    zpb = q1.1.2 - q1.2.1 -              1*(q1.2.1 - q1.2.1),
    zpm = q1.1.3 - q1.2.3 -              1*(q1.2.3 - q1.2.3),
    zaw = q2.1.1 - q2.2.2 - (1 - q2.3/100)*(q1.2.2 - q2.2.2),
    zab = q2.1.2 - q2.2.1 - (1 - q2.3/100)*(q1.2.1 - q2.2.1),
    zam = q2.1.3 - q2.2.3 - (1 - q2.3/100)*(q1.2.3 - q2.2.3),
    znw = q3.1.1 - q3.2.2 - (1 - q3.3/100)*(q1.2.2 - q3.2.2),
    znb = q3.1.2 - q3.2.1 - (1 - q3.3/100)*(q1.2.1 - q3.2.1),
    znm = q3.1.3 - q3.2.3 - (1 - q3.3/100)*(q1.2.3 - q3.2.3)
  ) %>% 
  mutate(
    id = letters[1:length(status)]
  ) %>% 
  select(
    species, status, zpw, zpb, zpm, zaw, zab, zam, znw, znb, znm
  ) %>% 
  gather(-species, -status, key = "measure", value = "zeta") %>%
  rowwise %>% 
  mutate(
    decision = str_split_fixed(measure, "", n = 3)[2],
    risk_scenario = str_split_fixed(measure, "", n = 3)[3]
    ) %>% 
  select(-measure) %>% 
  mutate(
    status = case_when(status == "part" ~ "Part",
                       status == "pub" ~ "Public",
                       TRUE ~ "Secret"),
    decision = case_when(decision == "p" ~ "Public",
                       decision == "a" ~ "Part",
                       TRUE ~ "Secret"),
    decision = factor(decision, levels = c("Public", "Part", "Secret")),
    risk_scenario = case_when(risk_scenario == "m" ~ "Most likely",
                     risk_scenario == "b" ~ "Best case",
                     TRUE ~ "Worst case"),
    risk_scenario = factor(
      risk_scenario,
      levels = c(
        "Best case",
        "Most likely",
        "Worst case"
      )
    )
  ) %>%
  group_by(species, risk_scenario) %>%
  mutate(maxval = max(zeta)) %>%
  ungroup %>%
  mutate(optimal = ifelse(zeta == maxval, "optimal", "not optimal")) %>%
  select(-maxval) %>%
  filter(!is.na(zeta))

numeric_results
```

```{r figure_2}
figure_2 <- ggplot(data = numeric_results) +
  geom_hline(
    yintercept = 0,
    colour = "darkgrey"
  ) +
  geom_point(
    aes(
      x = decision,
      y = zeta,
      colour = risk_scenario,
      shape = optimal,
      size = optimal
    )
  ) +
  facet_wrap(
    facets = ~ species,
    nrow = 2,
    scales = "free_y"
  ) +
  theme(
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank(),
    axis.title.y = element_text(
      angle = 0
    )
  ) +
  ylab("Decision\nscore") +
  xlab("Decision to disclose") +
  scale_colour_manual(
    values = viridis(3),
    guide = guide_legend(
      title = "Risk\nscenario",
      direction = "vertical"
    ) 
  ) +
  scale_shape_manual(
    values = c(19, 17),
    guide = guide_legend(
      title = "Decision is\noptimal?",
      direction = "vertical"
    )
  ) +
  scale_size_manual(
    values = c(4, 5),
    guide = guide_legend(
      title = "Decision is\noptimal?",
      direction = "vertical"
    )
  ) + 
  expand_limits(y = 0)

figure_2
```



Table S3
```{r table_s3}
table_s3 <- numeric_results %>%
  select(-status, -optimal) %>%
  pivot_wider(
    names_from = decision,
    values_from = zeta
  ) %>%
  arrange(species, risk_scenario)

table_s3
```




Figure s1 - plots for each species
```{r figure s1}
figure_s1a <- s1_plot_fun("Alpine tree-frog")
figure_s1b <- s1_plot_fun("Giant Ibis")
figure_s1c <- s1_plot_fun("Red Handfish")
figure_s1d <- s1_plot_fun("Smooth Newt")
figure_s1e <- s1_plot_fun("Species1")
figure_s1f <- s1_plot_fun("Tiger")
figure_s1g <- s1_plot_fun("Wollemi Pine") +
    scale_colour_manual(
      values = viridis(3)[c(1,3)],
      guide = FALSE
    )
```


```{r}
figure_s1 <- figure_s1a +
  figure_s1b +
  figure_s1c +
  figure_s1d +
  figure_s1e +
  figure_s1f +
  figure_s1g +
  guide_area() +
  plot_layout(
    ncol = 1,
    guides = "collect"
  ) +
  plot_annotation(
    tag_levels = "a"
  )

figure_s1
```
