---
title: 'Data analysis and graphics for: The costs and benefits of publicising species
  discoveries.'
author: "GE Ryan"
output:
  html_notebook: default
  pdf_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r packages}
library(dplyr)
library(ggplot2)
library(tidyr)
library(stringr)
library(readxl)
library(viridis)
library(patchwork)
library(magrittr)
library(purrr)
```

```{r source functions}
source("functions/s1_plot_fun.R")
source("functions/find.sd.R")
```


# Example scenarios

Load data
```{r load example}
example_data <- readxl::read_xlsx(
  path = "data/species_publicity_data.xlsx",
  sheet = "example_case_studies"
)

example_data
```
Calculate decision score, zeta, for each option
```{r example_results}
example_results <- example_data %>%
  as_tibble %>%
  mutate(
    zeta = benefit - cost - probability_of_leaking*(cost_of_publicity - cost),
    involve = factor(
      involve,
      levels = c(
        "Government",
        "Local community group",
        "Public"
      )
    ),
    disclose = factor(
      disclose,
      levels = c(
        "Nothing",
        "Province",
        "Protected area",
        "Exact location"
      ),
    ),
    disclose = recode(
      disclose,
      "Protected area" = "Protected\narea",
      "Exact location" = "Exact\nlocation"
    )
  ) %>%
  group_by(species) %>%
  mutate(
    maxval = max(zeta)
  ) %>%
  ungroup %>%
  mutate(
    optimal = ifelse(
      zeta == maxval,
      "optimal",
      "not optimal"
    )
  ) %>%
  select(-maxval)

example_results
```

Plot results from examples scenarios in figure 1.
```{r figure_1}
figure_1 <- ggplot(example_results) +
  geom_hline(
    yintercept = 0,
    colour = "darkgrey"
  ) +
  geom_point(
    aes(
      x = disclose,
      y = zeta,
      colour = involve,
      shape = optimal,
      size = optimal
    ),
    position = position_dodge(
      width = 0.1)
  ) +
  facet_wrap(
    facets = ~ species,
    nrow = 2,
    scales = "free_y"
  ) +
  theme_grey() +
  theme(
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank(),
    axis.title.y = element_text(
      angle = 0
    ),
    axis.text.x = element_text(
      angle = 90
    )#,
    #legend.position = "bottom"
  ) +
  ylab("Decision\nscore") +
  xlab("Decision to disclose") +
  scale_colour_manual(
    values = plasma(11)[c(2,6,10)],
    guide = guide_legend(
      title = "Decision to\ninvolve",
      direction = "vertical"
    )
  ) +
  scale_shape_manual(
    values = c(19, 17),
    guide = guide_legend(
      title = "Decision is\noptimal?",
      direction = "vertical"
    )
  ) +
  scale_size_manual(
    values = c(4, 5),
    guide = guide_legend(
      title = "Decision is\noptimal?",
      direction = "vertical"
    )
  ) 

figure_1
```

```{r figure_1 png}
png(
  filename = "plots/figure_1.png",
  width = 20,
  height = 12.5,
  units = "cm",
  res = 300
)
figure_1
dev.off()
```


```{r}
table_s2 <- example_results %>%
  select(species, disclose, involve, zeta) %>% 
  pivot_wider(
    names_from = disclose,
    values_from = zeta
  ) %>%
  arrange(species, involve)

table_s2
```

```{r write table_s2}
write.csv(
  x = table_s2,
  file = "output/table_s2.csv",
  row.names = FALSE
)
```

# Questionnaire numeric estimates of cost and benefits

```{r numeric_data}
numeric_data <- readxl::read_xlsx(
  path = "data/species_publicity_data.xlsx",
  sheet = "questionnaire_numeric"
)


numeric_data[ , which(substr(colnames(numeric_data), 1,1) == "q")] <- apply(
  X = numeric_data[ , which(substr(colnames(numeric_data), 1,1) == "q")],
  MARGIN = 2,
  FUN = as.numeric
)

numeric_data
```

```{r}
numdat <- numeric_data %>%
  select(
    -status,
    -currency,
    -consent_sp_id,
    -consent_sp_loc,
    -sp_loc
  ) %>%
  pivot_longer(
    cols = starts_with("q"),
    names_to = "question",
  ) %>%
  mutate(
    decision = substr(
      x = question,
      start = 2,
      stop = 2
    ) %>%
      as.integer,
    type = substr(
      x = question,
      start = 4,
      stop = 4
    ) %>%
      as.integer,
    estimate = substr(
      x = question,
      start = 6,
      stop = 6
    ) %>%
      as.integer
  ) %>%
  mutate(
    decision = case_when(
      decision == 1 ~ "Public",
      decision == 2 ~ "Part",
      decision == 3 ~ "Secret"
    ),
    type = case_when(
      type == 1 ~ "Benefit",
      type == 2 ~ "Cost",
      type == 3 ~ "pleak"
    ),
    estimate = case_when(
      estimate == 1 ~ "lower",
      estimate == 2 ~ "upper",
      estimate == 3 ~ "mid",
      estimate == 4 ~ "pconf"
    )
  ) %>%
  select(
    species,
    decision,
    type,
    estimate,
    value
  )

numdat
```


```{r}
numdat_cb <- numdat %>%
  filter(type != "pleak") %>%
  pivot_wider(
    names_from = estimate,
    values_from = value
  ) %>%
  mutate(
    pconf = pconf/100
  ) %>%
  filter(species != "Species2") %>%
  mutate(
    mid = ifelse(
      test = is.na(mid),
      yes = (upper - lower)/2,
      no = mid
    ),
    pconf = ifelse(
      test = is.na(pconf),
      yes = 0.95,
      no = pconf
    ),
    dist = case_when(
      pconf == 1 ~ "triangular",
      lower == mid ~ "exponential",
      lo
      #(lower == 0) & (pconf <= 0.5) ~ "", # need to tweak mode vs mean though - thou
      TRUE ~ "lognormal"
    )
  )


numdat_cb
```
what to do about tiger whgere low prob means can't fit typical lnorm or 
```{r}
numdat_cb %>%
  mutate(
    dist = case_when(
      pc
    )
  )
```


```{r}
numdat_cb_sd <- numdat_cb %>%
  mutate(
    sd = pmap(
      .l = list(
        lower = lower,
        mid = mid,
        upper = upper,
        p = pconf
      ),
      .f = find.sd,,
      print.sd = FALSE
    )
  ) %>%
  unnest(sd)

numdat_cb_sd
```

```{r}
# for(i in 1:38){
# 
#   print(paste("Yay", i))
# 
# x <- i

x <- 35

sd5 <- find.sd(
  lower = numdat_cb$lower[x],
  mid = numdat_cb$mid[x],
  upper = numdat_cb$upper[x],
  p = numdat_cb$pconf[x]
)

# }
```



```{r}
x <- 5

lower <- numdat_cb$lower[x]
mid <- numdat_cb$mid[x]
upper <- numdat_cb$upper[x]
p <- numdat_cb$pconf[x]

  ll <- log(lower)
  lm <- log(mid)
  lu <- log(upper)
  
  probs1 <- pnorm(
    q = c(ll, lu),
    mean = lm,
    sd = 1
  )
  
  prob.width <- probs1[2] - probs1[1]
  
  diff <- abs(p - prob.width)
  
  if(diff <= tolerance){
    return(1)
  }
  
  if(prob.width > p){
    sd_seq <- seq(
      from = 1,
      to = 10e6,
      length.out = 1000
    )
  } else{
    sd_seq <- seq(
      from = 0,
      to = 1,
      length.out = 1000
    )
  }
  
  while(diff > tolerance){
    probs_upper <- pnorm(
      q = lu,
      mean = lm,
      sd = sd_seq
    )
    
    probs_lower <- pnorm(
      q = ll,
      mean = lm,
      sd = sd_seq
    )
    
    diffs <- p - (probs_upper - probs_lower)
    
    diffs.above <- diffs[which(diffs > 0)]
    diffs.below <- diffs[which(diffs < 0)]
    
    diff.above <- min(diffs.above)
    diff.below <- max(diffs.below)
    
    diff <- min(diff.above, abs(diff.below))
    
    index.above <- which(diffs == diff.above)[1]
    index.below <- which(diffs == diff.below)[length(which(diffs == diff.below))]
    
    sd.above <- sd_seq[index.above]
    sd.below <- sd_seq[index.below]
    
    sd <- ifelse(
      diff == diff.above,
      sd.above,
      sd.below
    )
    
    sd_seq <- seq(
      from = sd.below,
      to = sd.above,
      length.out = 1000
    )
    
    if(print.sd){
      print(sd)
      print(diff)
    }
    
  }
  
```


```{r}
lower <- numdat_cb$lower[x]
most.likely <- numdat_cb$mid[x]
upper <- numdat_cb$upper[x]
p <- numdat_cb$pconf[x]

  sigma <- 1:10
  
  mu <- log(most.likely) + sigma
  
plnorm(
    q = ,
    meanlog = mu,
    sdlog = s
  )
```


```{r}
x <- 5

lower <- numdat_cb$lower[x]
most.likely <- numdat_cb$mid[x]
upper <- numdat_cb$upper[x]
p <- numdat_cb$pconf[x]

  sigma <- 1
  
  mu <- log(most.likely) + (sigma^2)
  
  probs1 <- plnorm(
    q = c(lower, upper),
    meanlog = mu,
    sdlog = sigma
  )
  
  prob.width <- probs1[2] - probs1[1]
  
  diff <- abs(p - prob.width)
  
  if(diff <= tolerance){
    return(1)
  }
  
  if(prob.width > p){
    sd_seq <- seq(
      from = 1,
      to = 10e6,
      length.out = 1000
    )
  } else{
    sd_seq <- seq(
      from = 0,
      to = 1,
      length.out = 1000
    )
  }
  
  mu_seq <- log(most.likely) + (sigma^2)
  
  while(diff > tolerance){
    probs_upper <- plnorm(
      q = lower,
      meanlog = mu_seq,
      sdlog = sd_seq
    )
    
    probs_lower <- plnorm(
      q = ll,
      mean = lm,
      sd = sd_seq
    )
    
    diffs <- p - (probs_upper - probs_lower)
    
    diffs.above <- diffs[which(diffs > 0)]
    diffs.below <- diffs[which(diffs < 0)]
    
    diff.above <- min(diffs.above)
    diff.below <- max(diffs.below)
    
    diff <- min(diff.above, abs(diff.below))
    
    index.above <- which(diffs == diff.above)[1]
    index.below <- which(diffs == diff.below)[length(which(diffs == diff.below))]
    
    sd.above <- sd_seq[index.above]
    sd.below <- sd_seq[index.below]
    
    sd <- ifelse(
      diff == diff.above,
      sd.above,
      sd.below
    )
    
    sd_seq <- seq(
      from = sd.below,
      to = sd.above,
      length.out = 1000
    )
    
    if(print.sd){
      print(sd)
      print(diff)
    }
    
  }
  
```


```{r}
l <- numeric_data$q1.1.1[[1]]
u <- numeric_data$q1.1.2[[1]]
m <- numeric_data$q1.1.3[[1]]

ll <- log(l)
lu <- log(u)
lm <- log(m)

ll
lu
lm
```

```{r}
sd <- 1

probs <- pnorm(
  q = c(ll, lu),
  mean = lm,
  sd = sd
)



probs

probs[2] - probs[1]

```


```{r}
lower <- numeric_data$q1.1.1[1]
upper <- numeric_data$q1.1.2[1]
mid <- numeric_data$q1.1.3[1]
p <- numeric_data$q1.1.4[1]/100

#tolerance <- 10e-9

aa <- find.sd(
  lower = lower,
  upper = upper,
  mid = mid,
  p = p,
  tolerance = 1e-9
)
```

```{r}
zz <- pnorm(
  q = c(ll, lu),
  mean = lm,
  sd = aa
)

zz

zz[2] - zz[1]
```

```{r}
numeric_results <- numeric_data %>%
  as_tibble %>% 
  mutate(
    zpw = q1.1.1 - q1.2.2 -              1*(q1.2.2 - q1.2.2),
    zpb = q1.1.2 - q1.2.1 -              1*(q1.2.1 - q1.2.1),
    zpm = q1.1.3 - q1.2.3 -              1*(q1.2.3 - q1.2.3),
    zaw = q2.1.1 - q2.2.2 - (1 - q2.3/100)*(q1.2.2 - q2.2.2),
    zab = q2.1.2 - q2.2.1 - (1 - q2.3/100)*(q1.2.1 - q2.2.1),
    zam = q2.1.3 - q2.2.3 - (1 - q2.3/100)*(q1.2.3 - q2.2.3),
    znw = q3.1.1 - q3.2.2 - (1 - q3.3/100)*(q1.2.2 - q3.2.2),
    znb = q3.1.2 - q3.2.1 - (1 - q3.3/100)*(q1.2.1 - q3.2.1),
    znm = q3.1.3 - q3.2.3 - (1 - q3.3/100)*(q1.2.3 - q3.2.3)
  ) %>% 
  mutate(
    id = letters[1:length(status)]
  ) %>% 
  select(
    species, status, zpw, zpb, zpm, zaw, zab, zam, znw, znb, znm
  ) %>% 
  gather(-species, -status, key = "measure", value = "zeta") %>%
  rowwise %>% 
  mutate(
    decision = str_split_fixed(measure, "", n = 3)[2],
    risk_scenario = str_split_fixed(measure, "", n = 3)[3]
    ) %>% 
  select(-measure) %>% 
  mutate(
    status = case_when(status == "part" ~ "Part",
                       status == "pub" ~ "Public",
                       TRUE ~ "Secret"),
    decision = case_when(decision == "p" ~ "Public",
                       decision == "a" ~ "Part",
                       TRUE ~ "Secret"),
    decision = factor(decision, levels = c("Public", "Part", "Secret")),
    risk_scenario = case_when(risk_scenario == "m" ~ "Most likely",
                     risk_scenario == "b" ~ "Best case",
                     TRUE ~ "Worst case"),
    risk_scenario = factor(
      risk_scenario,
      levels = c(
        "Best case",
        "Most likely",
        "Worst case"
      )
    )
  ) %>%
  group_by(species, risk_scenario) %>%
  mutate(maxval = max(zeta)) %>%
  ungroup %>%
  mutate(optimal = ifelse(zeta == maxval, "optimal", "not optimal")) %>%
  select(-maxval) %>%
  filter(!is.na(zeta))

numeric_results
```

```{r figure_2}
figure_2 <- ggplot(data = numeric_results) +
  geom_hline(
    yintercept = 0,
    colour = "darkgrey"
  ) +
  geom_point(
    aes(
      x = decision,
      y = zeta,
      colour = risk_scenario,
      shape = optimal,
      size = optimal
    )
  ) +
  facet_wrap(
    facets = ~ species,
    nrow = 2,
    scales = "free_y"
  ) +
  theme(
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank(),
    axis.title.y = element_text(
      angle = 0
    )
  ) +
  ylab("Decision\nscore") +
  xlab("Decision to disclose") +
  scale_colour_manual(
    values = viridis(3),
    guide = guide_legend(
      title = "Risk\nscenario",
      direction = "vertical"
    ) 
  ) +
  scale_shape_manual(
    values = c(19, 17),
    guide = guide_legend(
      title = "Decision is\noptimal?",
      direction = "vertical"
    )
  ) +
  scale_size_manual(
    values = c(4, 5),
    guide = guide_legend(
      title = "Decision is\noptimal?",
      direction = "vertical"
    )
  ) + 
  expand_limits(y = 0)

figure_2
```

```{r figure_2 png}
png(
  filename = "plots/figure_2.png",
  width = 20,
  height = 12.5,
  units = "cm",
  res = 300
)
figure_2
dev.off()
```


Table S3
```{r table_s3}
table_s3 <- numeric_results %>%
  select(-status, -optimal) %>%
  pivot_wider(
    names_from = decision,
    values_from = zeta
  ) %>%
  arrange(species, risk_scenario)

table_s3
```

```{r write table_s3}
write.csv(
  x = table_s3,
  file = "output/table_s3.csv",
  row.names = FALSE
)
```


Figure s1 - plots for each species
```{r figure s1}
figure_s1a <- s1_plot_fun("Alpine tree-frog")
figure_s1b <- s1_plot_fun("Giant Ibis")
figure_s1c <- s1_plot_fun("Red Handfish")
figure_s1d <- s1_plot_fun("Smooth Newt")
figure_s1e <- s1_plot_fun("Species1")
figure_s1f <- s1_plot_fun("Tiger")
figure_s1g <- s1_plot_fun("Wollemi Pine") +
    scale_colour_manual(
      values = viridis(3)[c(1,3)],
      guide = FALSE
    )
```


```{r}
figure_s1 <- figure_s1a +
  figure_s1b +
  figure_s1c +
  figure_s1d +
  figure_s1e +
  figure_s1f +
  figure_s1g +
  guide_area() +
  plot_layout(
    ncol = 1,
    guides = "collect"
  ) +
  plot_annotation(
    tag_levels = "a"
  )

figure_s1
```

```{r}
png(
  filename = "plots/figure_s1.png",
  width = 20,
  height = 32,
  units = "cm",
  res = 300
)
figure_s1
dev.off()
```

# Questionnaire written responses on types of costs and benefits
```{r text_dat}
text_dat <- readxl::read_xlsx(
  path = "data/species_publicity_data.xlsx",
  sheet = "questionnaire_text"
)
```

```{r }
q_numeric <- sapply(text_dat, is.numeric)
sum_resp <- sapply(
  X = text_dat,
  FUN = function(x){
    
    isnum <- is.numeric(x)
    
    if(isnum){
      result <- sum(x, na.rm = TRUE)
    } else {
      result <- NA
    }
    
  }
)

perc_resp <- sapply(
  X = text_dat,
  FUN = function(x){
    
    isnum <- is.numeric(x)
    
    lenx <- length(x)
    
    if(isnum){
      result <- 100*sum(x, na.rm = TRUE)/lenx
    } else {
      result <- NA
    }
    
  }
)

text_results <- tibble(
  question = colnames(text_dat),
  sum_responses = sum_resp,
  percentage_responses = perc_resp
)

text_results
```

```{r}
all_results <- text_results %>%
  filter(substr(question, 1, 3) == "all") %>%
  mutate(
    c1 = sub(
      pattern = ".{0,4}_",
      replacement = "",
      question
    ),
    c2 = sub(
      pattern = ".{0,8}_",
      replacement = "",
      c1
    ),
    cost_benefit= sub(
      pattern = "_.*",
      replacement = "",
      c1
    ),
    group = sub(
      pattern = "_.*",
      replacement = "",
      c2
    ),
    response = sub(
      pattern = ".{0,8}_",
      replacement = "",
      c2
    )
  ) %>%
  select(cost_benefit, group, response, sum_responses, percentage_responses) %>%
  mutate(
    response = recode(
      response,
      "funding" = "Funding",
      "awareness-publicsupport" = "Awareness &\npublic support",
      "protection-recovery" = "Protection &\nrecovery",
      "species" = "Species",
      "individuals" = "Individual\npeople",
      "researchersandinstitutes" = "Researchers &\ninstitutes",
      "gov" = "Government",
      "business" = "Business",
      "ngo" = "NGOs",
      "genpublic" = "General\npublic",
      "genpub" = "General\npublic",
      "poaching" = "Poaching",
      "extinctionextirpation" = "Extinction &\nextirpation",
      "disease" = "Disease",
      "funding-financial" = "Funding",
      "reputation" = "Reputation"
    )
  )

all_results
```


```{r}
benefits <- all_results %>% filter(cost_benefit == "benefits")
costs <- all_results %>% filter(cost_benefit == "costs")

benefits_kind     <- benefits %>% filter(group == "kind")
benefits_entities <- benefits %>% filter(group == "entities")
benefits_source   <- benefits %>% filter(group == "source")

costs_kind     <- costs %>% filter(group == "kind")
costs_entities <- costs %>% filter(group == "entities")
```


```{r}
figure_3a <- ggplot(benefits_kind) +
  geom_bar(
    aes(
      x = response,
      y = percentage_responses
    ),
    fill = viridis(9)[8],
    stat = "identity",
    width = 0.9*3/7
  ) +
  ylab("Percentage of informants") +
  xlab("Kinds of benefit") +
  ylim(0, 100)

figure_3a
```

```{r}
figure_3b <- ggplot(benefits_entities) +
  geom_bar(
    aes(
      x = response,
      y = percentage_responses
    ),
    fill = viridis(9)[8],
    stat = "identity",
    width = 0.9
  ) +
  ylab("Percentage of informants") +
  xlab("Entities recieving benefits") +
  ylim(0, 100)

figure_3b
```

```{r}
figure_3c <- ggplot(benefits_source) +
  geom_bar(
    aes(
      x = response,
      y = percentage_responses
    ),
    fill = viridis(9)[8],
    stat = "identity",
    width = 0.9*3/7
  ) +
  ylab("Percentage of informants") +
  xlab("Source of benefits") +
  ylim(0, 100)

figure_3c
```

```{r}
figure_3d <- ggplot(costs_kind) +
  geom_bar(
    aes(
      x = response,
      y = percentage_responses
    ),
    fill = viridis(9)[2],
    stat = "identity",
    width = 0.9*5/7
  ) +
  ylab("Percentage of informants") +
  xlab("Kinds of cost") +
  ylim(0, 100)

figure_3d
```

```{r}
figure_3e <- ggplot(costs_entities) +
  geom_bar(
    aes(
      x = response,
      y = percentage_responses
    ),
    fill = viridis(9)[2],
    stat = "identity",
    width = 0.9*3/7
  ) +
  ylab("Percentage of informants") +
  xlab("Entities bearing costs") +
  ylim(0, 100)

figure_3e
```

```{r}
figure_3 <- figure_3a +
  figure_3b +
  figure_3c +
  figure_3d +
  figure_3e +
  plot_layout(
    ncol = 1
  ) +
  plot_annotation(
    tag_levels = "a"
  )

figure_3
```

```{r}
png(
  filename = "plots/figure_3.png",
  width = 20,
  height = 32,
  units = "cm",
  res = 300
)
figure_3
dev.off()
```

